
#DEBUG = +define+SIMULATION=1
#DEFS = +define+HALFCYCLE=25 +define+W=6 +define+MAXTICKS=10000 +define+CODE_START=2000 +define+CODE=\"rom\" +define+RESET=2000
DEFS = +define+HALFCYCLE=70 +define+W=6 +define+MAXTICKS=10000 +define+CODE_START=2000 +define+CODE=\"rom\" +define+RESET=2000

test:
	cver $(DEFS) test_6502.v chip_6502.v clocks_6502.v ram_6502.v models.v 